services:
    galandas.tgtrad.listener:
        class: galandas\tgtrad\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'        
        tags:
            - { name: event.listener }
